// airbnb/lib/property-types.ts
export const PROPERTY_TYPES = [
  { value: "apartment", label: "Apartment" },
  { value: "house", label: "House" },
  { value: "villa", label: "Villa" },
  { value: "cabin", label: "Cabin" },
  { value: "condo", label: "Condo" },
  { value: "studio", label: "Studio" },
  { value: "loft", label: "Loft" },
  { value: "cottage", label: "Cottage" },
  { value: "townhouse", label: "Townhouse" },
  { value: "bungalow", label: "Bungalow" },
] as const;

export const AMENITIES = [
  "WiFi",
  "Kitchen",
  "Air conditioning",
  "Heating",
  "Washer",
  "Dryer",
  "Dishwasher",
  "Pool",
  "Hot tub",
  "Gym",
  "Fireplace",
  "BBQ",
  "Parking",
  "Elevator",
  "Beach access",
  "Garden",
  "Balcony",
  "Terrace",
  "City view",
  "Ocean view",
  "Mountain view",
  "Ski-in/ski-out",
  "Breakfast included",
  "Butler service",
  "Concierge",
  "Pet-friendly",
  "Wheelchair accessible",
  "Smoke detector",
  "Carbon monoxide detector",
  "First aid kit",
] as const;
