// airbnb/convex/seed.ts
import { mutation } from "./_generated/server";

const SEED_HOSTS = [
  {
    tokenIdentifier: "seed|host1",
    clerkId: "seed_host_1",
    email: "host1@seed.dev",
    name: "Alex Rivera",
    imageUrl: "https://picsum.photos/seed/host1/100/100",
    role: "host" as const,
  },
  {
    tokenIdentifier: "seed|host2",
    clerkId: "seed_host_2",
    email: "host2@seed.dev",
    name: "Priya Patel",
    imageUrl: "https://picsum.photos/seed/host2/100/100",
    role: "host" as const,
  },
  {
    tokenIdentifier: "seed|host3",
    clerkId: "seed_host_3",
    email: "host3@seed.dev",
    name: "Marco Bianchi",
    imageUrl: "https://picsum.photos/seed/host3/100/100",
    role: "host" as const,
  },
];

const SEED_PROPERTIES = [
  {
    title: "Luxury Manhattan Apartment",
    description: "Stunning high-rise apartment in the heart of Manhattan with breathtaking skyline views. Floor-to-ceiling windows, gourmet kitchen, and rooftop access.",
    type: "apartment", city: "New York", state: "NY", country: "USA",
    address: "432 Park Ave, New York, NY 10022",
    lat: 40.7614, lng: -73.9776,
    pricePerNight: 25000, cleaningFee: 5000,
    maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 2,
    amenities: ["WiFi", "Kitchen", "Air conditioning", "Washer", "Dryer", "Gym", "Doorman", "City view"],
    houseRules: ["No smoking", "No pets", "No parties", "Quiet hours after 10pm"],
    checkInTime: "15:00", checkOutTime: "11:00",
    minNights: 2, maxNights: 30, instantBook: true,
    coverImageUrl: "https://picsum.photos/seed/prop1/800/600",
    coverImagePublicId: "seed/prop1",
    hostIndex: 0,
  },
  {
    title: "Miami Beach Oceanfront Condo",
    description: "Wake up to ocean waves in this stunning beachfront condo. Direct beach access, infinity pool, and modern interiors designed for the ultimate Florida getaway.",
    type: "condo", city: "Miami", state: "FL", country: "USA",
    address: "1 Ocean Dr, Miami Beach, FL 33139",
    lat: 25.7825, lng: -80.1300,
    pricePerNight: 18000, cleaningFee: 4000,
    maxGuests: 6, bedrooms: 3, beds: 3, bathrooms: 2,
    amenities: ["WiFi", "Pool", "Beach access", "Kitchen", "Air conditioning", "Parking", "Balcony", "Ocean view"],
    houseRules: ["No smoking", "No parties", "Check-in after 3pm"],
    checkInTime: "15:00", checkOutTime: "10:00",
    minNights: 3, maxNights: 14, instantBook: false,
    coverImageUrl: "https://picsum.photos/seed/prop2/800/600",
    coverImagePublicId: "seed/prop2",
    hostIndex: 0,
  },
  {
    title: "Hollywood Hills Villa",
    description: "Iconic Hollywood Hills villa with panoramic LA views, private pool, home theater, and walking distance to the Griffith Observatory.",
    type: "villa", city: "Los Angeles", state: "CA", country: "USA",
    address: "2850 Outpost Dr, Los Angeles, CA 90068",
    lat: 34.1341, lng: -118.3215,
    pricePerNight: 55000, cleaningFee: 10000,
    maxGuests: 10, bedrooms: 5, beds: 6, bathrooms: 4,
    amenities: ["WiFi", "Pool", "Hot tub", "Home theater", "Kitchen", "BBQ", "Parking", "City view", "Air conditioning"],
    houseRules: ["No smoking indoors", "No events over 10 people", "Pets allowed with approval"],
    checkInTime: "16:00", checkOutTime: "11:00",
    minNights: 2, maxNights: 14, instantBook: false,
    coverImageUrl: "https://picsum.photos/seed/prop3/800/600",
    coverImagePublicId: "seed/prop3",
    hostIndex: 1,
  },
  {
    title: "Chicago Loop Studio",
    description: "Stylish studio in Chicago's vibrant Loop district. Walking distance to Millennium Park, the Art Institute, and all major attractions.",
    type: "studio", city: "Chicago", state: "IL", country: "USA",
    address: "190 S LaSalle St, Chicago, IL 60603",
    lat: 41.8799, lng: -87.6318,
    pricePerNight: 9500, cleaningFee: 2000,
    maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Air conditioning", "Washer", "City view", "Elevator"],
    houseRules: ["No smoking", "No pets", "Quiet after 11pm"],
    checkInTime: "15:00", checkOutTime: "11:00",
    minNights: 1, maxNights: 30, instantBook: true,
    coverImageUrl: "https://picsum.photos/seed/prop4/800/600",
    coverImagePublicId: "seed/prop4",
    hostIndex: 1,
  },
  {
    title: "Paris Montmartre Artist Apartment",
    description: "Charming 19th-century apartment in Montmartre, steps from Sacré-Cœur. Exposed stone walls, original hardwood floors, and a cosy French aesthetic.",
    type: "apartment", city: "Paris", state: "Île-de-France", country: "France",
    address: "12 Rue Lepic, 75018 Paris",
    lat: 48.8853, lng: 2.3345,
    pricePerNight: 17000, cleaningFee: 3500,
    maxGuests: 3, bedrooms: 1, beds: 2, bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Washer", "Heating", "City view"],
    houseRules: ["No smoking", "No parties", "Respect the neighbours"],
    checkInTime: "14:00", checkOutTime: "10:00",
    minNights: 3, maxNights: 21, instantBook: true,
    coverImageUrl: "https://picsum.photos/seed/prop5/800/600",
    coverImagePublicId: "seed/prop5",
    hostIndex: 2,
  },
  {
    title: "London Chelsea Victorian Flat",
    description: "Elegant Victorian flat in Chelsea, one of London's most prestigious neighbourhoods. High ceilings, sash windows, and a beautiful private garden.",
    type: "apartment", city: "London", state: "England", country: "UK",
    address: "45 Sloane Square, London SW1W 8AX",
    lat: 51.4925, lng: -0.1565,
    pricePerNight: 22000, cleaningFee: 5000,
    maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Garden", "Washer", "Dishwasher", "Heating"],
    houseRules: ["No smoking", "No parties", "Pets considered on request"],
    checkInTime: "15:00", checkOutTime: "11:00",
    minNights: 2, maxNights: 30, instantBook: false,
    coverImageUrl: "https://picsum.photos/seed/prop6/800/600",
    coverImagePublicId: "seed/prop6",
    hostIndex: 2,
  },
  {
    title: "Barcelona Gothic Quarter Piso",
    description: "Authentic apartment in the heart of Barcelona's Gothic Quarter. Steps from La Boqueria market and Las Ramblas. Sun-drenched terrace with city views.",
    type: "apartment", city: "Barcelona", state: "Catalonia", country: "Spain",
    address: "Carrer del Bisbe, 08002 Barcelona",
    lat: 41.3825, lng: 2.1769,
    pricePerNight: 12000, cleaningFee: 2500,
    maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Washer", "Terrace", "City view"],
    houseRules: ["No smoking", "No parties", "Quiet hours after 11pm"],
    checkInTime: "15:00", checkOutTime: "11:00",
    minNights: 2, maxNights: 21, instantBook: true,
    coverImageUrl: "https://picsum.photos/seed/prop7/800/600",
    coverImagePublicId: "seed/prop7",
    hostIndex: 0,
  },
  {
    title: "Tokyo Shinjuku Modern Studio",
    description: "Sleek minimalist studio in Shinjuku, perfectly positioned for exploring everything Tokyo has to offer. High-speed WiFi and capsule-hotel efficiency with apartment comfort.",
    type: "studio", city: "Tokyo", state: "Tokyo", country: "Japan",
    address: "2-1 Kabukicho, Shinjuku City, Tokyo 160-0021",
    lat: 35.6938, lng: 139.7034,
    pricePerNight: 9000, cleaningFee: 2000,
    maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Washer", "Elevator"],
    houseRules: ["No smoking", "No shoes indoors", "No guests after 11pm"],
    checkInTime: "15:00", checkOutTime: "10:00",
    minNights: 1, maxNights: 14, instantBook: true,
    coverImageUrl: "https://picsum.photos/seed/prop8/800/600",
    coverImagePublicId: "seed/prop8",
    hostIndex: 1,
  },
  {
    title: "Bali Ubud Jungle Villa",
    description: "Breathtaking villa nestled in the Ubud rice terraces. Private infinity pool, open-air dining, daily breakfast included, and a live-in housekeeper.",
    type: "villa", city: "Ubud", state: "Bali", country: "Indonesia",
    address: "Jl. Bisma, Ubud, Gianyar Regency, Bali 80571",
    lat: -8.5069, lng: 115.2625,
    pricePerNight: 28000, cleaningFee: 6000,
    maxGuests: 6, bedrooms: 3, beds: 3, bathrooms: 3,
    amenities: ["WiFi", "Pool", "Kitchen", "Breakfast included", "Air conditioning", "Garden", "Rice field view"],
    houseRules: ["No shoes in bedrooms", "No parties", "Respect local customs"],
    checkInTime: "14:00", checkOutTime: "12:00",
    minNights: 3, maxNights: 30, instantBook: false,
    coverImageUrl: "https://picsum.photos/seed/prop9/800/600",
    coverImagePublicId: "seed/prop9",
    hostIndex: 2,
  },
  {
    title: "Tuscany Farmhouse with Vineyard",
    description: "A restored 16th-century farmhouse surrounded by olive groves and vineyards near Florence. Stone fireplace, cellar tours, and stunning sunset views over the Chianti hills.",
    type: "house", city: "Florence", state: "Tuscany", country: "Italy",
    address: "Via Chiantigiana, 50022 Greve in Chianti FI",
    lat: 43.5840, lng: 11.3139,
    pricePerNight: 32000, cleaningFee: 7000,
    maxGuests: 8, bedrooms: 4, beds: 5, bathrooms: 3,
    amenities: ["WiFi", "Pool", "Kitchen", "BBQ", "Fireplace", "Parking", "Garden", "Wine cellar"],
    houseRules: ["No smoking indoors", "Pets allowed", "Quiet after midnight"],
    checkInTime: "16:00", checkOutTime: "10:00",
    minNights: 4, maxNights: 30, instantBook: false,
    coverImageUrl: "https://picsum.photos/seed/prop10/800/600",
    coverImagePublicId: "seed/prop10",
    hostIndex: 0,
  },
  {
    title: "Sydney Harbour View Apartment",
    description: "Spectacular apartment with unobstructed views of Sydney Harbour and the Opera House. Walk to the Circular Quay and explore the best of Sydney.",
    type: "apartment", city: "Sydney", state: "NSW", country: "Australia",
    address: "1 Macquarie St, Sydney NSW 2000",
    lat: -33.8614, lng: 151.2113,
    pricePerNight: 21000, cleaningFee: 4500,
    maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 2,
    amenities: ["WiFi", "Kitchen", "Air conditioning", "Washer", "Harbour view", "Gym", "Pool"],
    houseRules: ["No smoking", "No parties", "No shoes on carpet"],
    checkInTime: "15:00", checkOutTime: "10:00",
    minNights: 2, maxNights: 21, instantBook: true,
    coverImageUrl: "https://picsum.photos/seed/prop11/800/600",
    coverImagePublicId: "seed/prop11",
    hostIndex: 1,
  },
  {
    title: "Maldives Overwater Bungalow",
    description: "Live the ultimate island dream in a private overwater bungalow with a glass floor, direct lagoon access, and butler service included.",
    type: "house", city: "Malé", state: "Kaafu Atoll", country: "Maldives",
    address: "Veligandu Island, North Ari Atoll, Maldives",
    lat: 4.1755, lng: 72.9649,
    pricePerNight: 65000, cleaningFee: 12000,
    maxGuests: 2, bedrooms: 1, beds: 1, bathrooms: 1,
    amenities: ["WiFi", "Pool", "Ocean view", "Butler service", "Snorkeling equipment", "Kayak", "Air conditioning"],
    houseRules: ["No smoking on deck", "Couples only", "No outside food/drink"],
    checkInTime: "14:00", checkOutTime: "12:00",
    minNights: 3, maxNights: 14, instantBook: false,
    coverImageUrl: "https://picsum.photos/seed/prop12/800/600",
    coverImagePublicId: "seed/prop12",
    hostIndex: 2,
  },
  {
    title: "Brooklyn Williamsburg Loft",
    description: "Industrial-chic loft in the heart of Williamsburg, Brooklyn. Exposed brick, 14-foot ceilings, and walking distance to the best bars and restaurants in NYC.",
    type: "apartment", city: "New York", state: "NY", country: "USA",
    address: "100 N 7th St, Brooklyn, NY 11249",
    lat: 40.7178, lng: -73.9612,
    pricePerNight: 14000, cleaningFee: 3000,
    maxGuests: 4, bedrooms: 1, beds: 2, bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Washer", "Air conditioning", "Rooftop access"],
    houseRules: ["No smoking", "No parties over 8 people", "Pets welcome"],
    checkInTime: "15:00", checkOutTime: "11:00",
    minNights: 2, maxNights: 30, instantBook: true,
    coverImageUrl: "https://picsum.photos/seed/prop13/800/600",
    coverImagePublicId: "seed/prop13",
    hostIndex: 0,
  },
  {
    title: "Aspen Mountain Ski Cabin",
    description: "Cosy ski-in/ski-out cabin at the base of Aspen Mountain. Wood-burning fireplace, hot tub on the deck, and ski storage for your whole group.",
    type: "cabin", city: "Aspen", state: "CO", country: "USA",
    address: "123 Aspen Mountain Rd, Aspen, CO 81611",
    lat: 39.1878, lng: -106.8205,
    pricePerNight: 45000, cleaningFee: 9000,
    maxGuests: 8, bedrooms: 4, beds: 5, bathrooms: 3,
    amenities: ["WiFi", "Hot tub", "Fireplace", "Kitchen", "Ski storage", "Parking", "Mountain view"],
    houseRules: ["No smoking indoors", "Pets allowed", "Ski-in/ski-out etiquette"],
    checkInTime: "16:00", checkOutTime: "10:00",
    minNights: 3, maxNights: 14, instantBook: false,
    coverImageUrl: "https://picsum.photos/seed/prop14/800/600",
    coverImagePublicId: "seed/prop14",
    hostIndex: 1,
  },
  {
    title: "Copenhagen Design Apartment",
    description: "Minimalist Scandinavian apartment in the hip Nørrebro district. Danish design throughout, bicycle included, and steps from the city's best cafés.",
    type: "apartment", city: "Copenhagen", state: "Capital Region", country: "Denmark",
    address: "Nørrebrogade 45, 2200 Copenhagen",
    lat: 55.6889, lng: 12.5479,
    pricePerNight: 15500, cleaningFee: 3000,
    maxGuests: 3, bedrooms: 1, beds: 1, bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Washer", "Heating", "Bicycle", "Elevator"],
    houseRules: ["No smoking", "No shoes indoors", "Bicycle must be locked outside"],
    checkInTime: "15:00", checkOutTime: "11:00",
    minNights: 2, maxNights: 21, instantBook: true,
    coverImageUrl: "https://picsum.photos/seed/prop15/800/600",
    coverImagePublicId: "seed/prop15",
    hostIndex: 2,
  },
  {
    title: "Santorini Caldera Cave House",
    description: "Iconic cave house carved into the volcanic cliff in Oia with a private plunge pool and legendary caldera views. Watch the world-famous Santorini sunset from your terrace.",
    type: "house", city: "Santorini", state: "South Aegean", country: "Greece",
    address: "Oia 847 02, Santorini",
    lat: 36.4618, lng: 25.3753,
    pricePerNight: 38000, cleaningFee: 7500,
    maxGuests: 2, bedrooms: 1, beds: 1, bathrooms: 1,
    amenities: ["WiFi", "Plunge pool", "Air conditioning", "Caldera view", "Terrace", "Concierge"],
    houseRules: ["No smoking", "Adults only", "Quiet after midnight"],
    checkInTime: "15:00", checkOutTime: "11:00",
    minNights: 3, maxNights: 14, instantBook: false,
    coverImageUrl: "https://picsum.photos/seed/prop16/800/600",
    coverImagePublicId: "seed/prop16",
    hostIndex: 0,
  },
  {
    title: "Dubai Marina Penthouse",
    description: "Lavish penthouse in the Dubai Marina with 360° views of the skyline, private rooftop pool, and concierge service. Walking distance to the beach and world-class dining.",
    type: "apartment", city: "Dubai", state: "Dubai", country: "UAE",
    address: "Dubai Marina Walk, Dubai Marina, Dubai",
    lat: 25.0819, lng: 55.1367,
    pricePerNight: 42000, cleaningFee: 8500,
    maxGuests: 6, bedrooms: 3, beds: 3, bathrooms: 3,
    amenities: ["WiFi", "Pool", "Gym", "Air conditioning", "Kitchen", "Parking", "Concierge", "Marina view"],
    houseRules: ["No smoking", "No parties", "Dress code in lobby"],
    checkInTime: "15:00", checkOutTime: "12:00",
    minNights: 2, maxNights: 30, instantBook: true,
    coverImageUrl: "https://picsum.photos/seed/prop17/800/600",
    coverImagePublicId: "seed/prop17",
    hostIndex: 1,
  },
  {
    title: "Mexico City Condesa Casita",
    description: "Charming casita in Mexico City's tree-lined Condesa neighbourhood. Art Deco architecture, private patio, and within walking distance of dozens of world-class restaurants.",
    type: "house", city: "Mexico City", state: "CDMX", country: "Mexico",
    address: "Av. Ámsterdam 123, Hipódromo, 06100 Ciudad de México",
    lat: 19.4096, lng: -99.1685,
    pricePerNight: 8500, cleaningFee: 2000,
    maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Air conditioning", "Patio", "Washer", "Parking"],
    houseRules: ["No smoking", "No parties", "Pets welcome"],
    checkInTime: "14:00", checkOutTime: "12:00",
    minNights: 2, maxNights: 30, instantBook: true,
    coverImageUrl: "https://picsum.photos/seed/prop18/800/600",
    coverImagePublicId: "seed/prop18",
    hostIndex: 2,
  },
  {
    title: "Cape Town Clifton Ocean Villa",
    description: "Stunning contemporary villa above Clifton's famous 4th Beach. Infinity pool, wine cellar, home cinema, and panoramic views of the Atlantic Ocean and the Twelve Apostles mountain range.",
    type: "villa", city: "Cape Town", state: "Western Cape", country: "South Africa",
    address: "Clifton, Cape Town, 8005",
    lat: -33.9403, lng: 18.3718,
    pricePerNight: 38000, cleaningFee: 8000,
    maxGuests: 10, bedrooms: 5, beds: 6, bathrooms: 4,
    amenities: ["WiFi", "Pool", "Kitchen", "Home cinema", "Wine cellar", "BBQ", "Parking", "Ocean view"],
    houseRules: ["No smoking indoors", "No events over 15 people", "Quiet after midnight"],
    checkInTime: "15:00", checkOutTime: "11:00",
    minNights: 3, maxNights: 21, instantBook: false,
    coverImageUrl: "https://picsum.photos/seed/prop19/800/600",
    coverImagePublicId: "seed/prop19",
    hostIndex: 0,
  },
  {
    title: "Kyoto Traditional Machiya Townhouse",
    description: "A beautifully restored 100-year-old machiya (wooden townhouse) in central Kyoto. Zen garden, tatami rooms, and an authentic Japanese cypress wood bath.",
    type: "house", city: "Kyoto", state: "Kyoto", country: "Japan",
    address: "Nakagyo Ward, Kyoto, 604-8186",
    lat: 35.0116, lng: 135.7681,
    pricePerNight: 17500, cleaningFee: 4000,
    maxGuests: 6, bedrooms: 3, beds: 3, bathrooms: 2,
    amenities: ["WiFi", "Japanese bath", "Zen garden", "Kitchen", "Air conditioning", "Tatami rooms"],
    houseRules: ["No shoes indoors", "No smoking", "Respect the traditional decor", "Quiet after 10pm"],
    checkInTime: "15:00", checkOutTime: "11:00",
    minNights: 2, maxNights: 21, instantBook: false,
    coverImageUrl: "https://picsum.photos/seed/prop20/800/600",
    coverImagePublicId: "seed/prop20",
    hostIndex: 1,
  },
];

export const seedDatabase = mutation({
  args: {},
  handler: async (ctx) => {
    // Guard: only run once
    const existing = await ctx.db
      .query("config")
      .withIndex("by_key", (q) => q.eq("key", "seedRan"))
      .unique();

    if (existing) return { message: "Seed already ran", skipped: true };

    // Create seed host users
    const hostIds = [];
    for (const host of SEED_HOSTS) {
      const id = await ctx.db.insert("users", host);
      hostIds.push(id);
    }

    // Create 20 properties
    for (const prop of SEED_PROPERTIES) {
      const { hostIndex, ...propertyData } = prop;
      await ctx.db.insert("properties", {
        ...propertyData,
        hostId: hostIds[hostIndex],
        avgRating: Math.round((3.5 + Math.random() * 1.5) * 10) / 10,
        reviewCount: Math.floor(Math.random() * 80) + 5,
        status: "published",
      });
    }

    // Mark seed as complete
    await ctx.db.insert("config", { key: "seedRan", value: "true" });

    return { message: "Seed complete", propertiesCreated: SEED_PROPERTIES.length };
  },
});
